name: Selenium Tests

on: 
    push:
      branches: [ main ]
    workflow_dispatch: # This enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          # Add any other Python dependencies your project needs here
          # For example:
          # pip install beautifulsoup4
          pip install robotframework-requests

      - name: Set Chrome executable (if needed)
        run: |
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV

      - name: Run Robot Framework tests
        run: |
          robot --outputdir results tests/api