name: Selenium Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure SeleniumLibrary is in this file

      - name: Set Chrome executable (if needed)
        run: |
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV

      - name: Run Robot Framework tests
        run: |
          robot --variable BROWSER:chrome --outputdir results tests/selenium